cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VITASDK}/share/vita.toolchain.cmake" CACHE PATH "toolchain file")
endif()
project(vitaos_ps C)
include("${VITASDK}/share/vita.cmake" REQUIRED)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -O2 -nostdlib")
add_executable(vitaos_ps vitaos_ps.c)
target_link_libraries(vitaos_ps SceCtrl_stub SceAppMgr_stub SceIofilemgr_stub SceLibKernel_stub SceKernelThreadMgr_stub)
set_target_properties(vitaos_ps PROPERTIES LINK_FLAGS "-nostdlib")
vita_create_self(vitaos_ps.suprx vitaos_ps CONFIG ${CMAKE_SOURCE_DIR}/vitaos_ps.yml UNSAFE)
